apiVersion: apps/v1
kind: Deployment
metadata:
   name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        # Set Limits for resources in k8s 
        resources:
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "128Mi"
            cpu: "500m"          
  #maxUnavailable is an optional field that specifies the maximum number of Pods that can be unavailable during the update process. 
   strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1                                                                                              